info:
  contact: {}
  description: task-pool API documentation
  title: task-pool API Documentation
  version: 1.0.0
paths: {}
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and your JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
